### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by hmil** [marc0der/gradle-spawn-plugin#35]
Many issues and PRs on this repo have been hanging for years without a response from the maintainer.

@marc0der , your plugin is very useful but the community wants more features. If you do not have the bandwidth required to support this project, could you at least consider transferring ownership of it?

**Comment by marc0der** [comment]
@hmil It hasn't been maintained for many years, and I no longer have capacity to do so.

Usually we don't transfer ownership of repos, we simply fork them. Feel free to do that, then you can carry on the good work! Good luck!

**Comment by hmil** [comment]
Thank you for your quick response. Forking a project the maintainer cares about can be seen as rude and counter-productive. Which is why I asked in the first place ;)

**Comment by marc0der** [comment]
The spirit of open source is that anyone can fork and redistribute as they want. Go crazy! ;-)
